#!/bin/bash

echo -n "파일/디렉토리 이름 입력 [enter] "
read filename


if [ ! -e "$filename" ]; then
    echo "...은 존재하지 않습니다."
    exit 1
fi

if [ -L "$filename" ]; then
    type="심볼릭링크"
elif [ -d "$filename" ]; then
    type="디렉토리"
elif [ -c "$filename" ]; then
    type="문자장치"
elif [ -b "$filename" ]; then
    type="블록장치"
elif [ -p "$filename" ]; then
    type="파이프"
elif [ -S "$filename" ]; then
    type="소켓"
elif [ -f "$filename" ]; then
    type="보통파일"
else
    type="알 수 없는 유형"
fi

echo "$filename 은 $type 입니다."
