#!/bin/bash
# longest-word : find longest string in a file

while [ -n "$1" ]; do
    if [ -r "$1" ]; then
        max_word=
        max_len=0
        
        # 파일 내부의 글자(문자열)들을 하나씩 추출하여 비교
        for i in $(strings "$1"); do
            len=$(echo "$i" | wc -c)
            if (( len > max_len )); then
                max_len=$len
                max_word=$i
            fi
        done
        echo "$1: '$max_word' ($max_len characters)"
    fi
    shift
done
